name: databank
volumes:
  caddy_data:
  mongo_data:
services:
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - '6000:80'
    environment:
      - SITE_ADDRESS
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
  api:
    image: ghcr.io/douglasneuroinformatics/databank-api:latest
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017
      - SECRET_KEY
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - VALIDATION_TIMEOUT
      - MAX_VALIDATION_ATTEMPTS
    expose:
      - 80
  web:
    image: ghcr.io/douglasneuroinformatics/databank-web:latest
    build:
      context: .
      dockerfile: ./web/Dockerfile
    expose:
      - 80
  mongo:
    image: mongo:6.0.2
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db
