name: databank-dev
services:
  mongo:
    image: mongo:${MONGO_VERSION}
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - ./data/configdb:/data/configdb
      - ./data/db:/data/db

  valkey:
    image: valkey/valkey:${VALKEY_VERSION}
    container_name: valkey
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${VALKEY_PORT}:${VALKEY_PORT}
    volumes:
      - ./valkey-data:/valkey-data
