name: databank-dev
services:
  mongo:
    image: mongo:7.0
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - '27017:27017'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - ./data/configdb:/data/configdb
      - ./data/db:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/redis-data
