catalog:
  '@douglasneuroinformatics/esbuild-plugin-native-modules': latest
  '@douglasneuroinformatics/esbuild-plugin-prisma': latest
  '@douglasneuroinformatics/eslint-config': latest
  '@douglasneuroinformatics/libjs': latest
  '@douglasneuroinformatics/libnest': latest
  '@douglasneuroinformatics/libpasswd': latest
  '@douglasneuroinformatics/libui': latest
  '@douglasneuroinformatics/libui-form-types': latest
  '@douglasneuroinformatics/prettier-config': latest
  '@douglasneuroinformatics/tsconfig': latest
  'type-fest': '^4.26.1'
  'zod': '^3.23.8'
packages:
  - api
  - core
  - web
