/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as PortalImport } from './routes/portal';
import { Route as IndexImport } from './routes/index';
import { Route as SetupIndexImport } from './routes/setup/index';
import { Route as PublicDatasetsImport } from './routes/public/datasets';
import { Route as AuthLoginImport } from './routes/auth/login';
import { Route as AuthCreateAccountImport } from './routes/auth/create-account';
import { Route as AuthConfirmEmailCodeImport } from './routes/auth/confirm-email-code';
import { Route as PortalUserIndexImport } from './routes/portal/user/index';
import { Route as PortalProjectsIndexImport } from './routes/portal/projects/index';
import { Route as PortalDatasetsIndexImport } from './routes/portal/datasets/index';
import { Route as PortalDashboardIndexImport } from './routes/portal/dashboard/index';
import { Route as PublicDatasetDatasetIdImport } from './routes/public/dataset.$datasetId';
import { Route as PortalProjectsCreateImport } from './routes/portal/projects/create';
import { Route as PortalDatasetsCreateImport } from './routes/portal/datasets/create';

// Create/Update Routes

const PortalRoute = PortalImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRoute
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any);

const SetupIndexRoute = SetupIndexImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRoute
} as any);

const PublicDatasetsRoute = PublicDatasetsImport.update({
  id: '/public/datasets',
  path: '/public/datasets',
  getParentRoute: () => rootRoute
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute
} as any);

const AuthCreateAccountRoute = AuthCreateAccountImport.update({
  id: '/auth/create-account',
  path: '/auth/create-account',
  getParentRoute: () => rootRoute
} as any);

const AuthConfirmEmailCodeRoute = AuthConfirmEmailCodeImport.update({
  id: '/auth/confirm-email-code',
  path: '/auth/confirm-email-code',
  getParentRoute: () => rootRoute
} as any);

const PortalUserIndexRoute = PortalUserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => PortalRoute
} as any);

const PortalProjectsIndexRoute = PortalProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PortalRoute
} as any);

const PortalDatasetsIndexRoute = PortalDatasetsIndexImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => PortalRoute
} as any);

const PortalDashboardIndexRoute = PortalDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PortalRoute
} as any);

const PublicDatasetDatasetIdRoute = PublicDatasetDatasetIdImport.update({
  id: '/public/dataset/$datasetId',
  path: '/public/dataset/$datasetId',
  getParentRoute: () => rootRoute
} as any);

const PortalProjectsCreateRoute = PortalProjectsCreateImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => PortalRoute
} as any);

const PortalDatasetsCreateRoute = PortalDatasetsCreateImport.update({
  id: '/datasets/create',
  path: '/datasets/create',
  getParentRoute: () => PortalRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/portal': {
      id: '/portal';
      path: '/portal';
      fullPath: '/portal';
      preLoaderRoute: typeof PortalImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/confirm-email-code': {
      id: '/auth/confirm-email-code';
      path: '/auth/confirm-email-code';
      fullPath: '/auth/confirm-email-code';
      preLoaderRoute: typeof AuthConfirmEmailCodeImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/create-account': {
      id: '/auth/create-account';
      path: '/auth/create-account';
      fullPath: '/auth/create-account';
      preLoaderRoute: typeof AuthCreateAccountImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/login': {
      id: '/auth/login';
      path: '/auth/login';
      fullPath: '/auth/login';
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof rootRoute;
    };
    '/public/datasets': {
      id: '/public/datasets';
      path: '/public/datasets';
      fullPath: '/public/datasets';
      preLoaderRoute: typeof PublicDatasetsImport;
      parentRoute: typeof rootRoute;
    };
    '/setup/': {
      id: '/setup/';
      path: '/setup';
      fullPath: '/setup';
      preLoaderRoute: typeof SetupIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/portal/datasets/create': {
      id: '/portal/datasets/create';
      path: '/datasets/create';
      fullPath: '/portal/datasets/create';
      preLoaderRoute: typeof PortalDatasetsCreateImport;
      parentRoute: typeof PortalImport;
    };
    '/portal/projects/create': {
      id: '/portal/projects/create';
      path: '/projects/create';
      fullPath: '/portal/projects/create';
      preLoaderRoute: typeof PortalProjectsCreateImport;
      parentRoute: typeof PortalImport;
    };
    '/public/dataset/$datasetId': {
      id: '/public/dataset/$datasetId';
      path: '/public/dataset/$datasetId';
      fullPath: '/public/dataset/$datasetId';
      preLoaderRoute: typeof PublicDatasetDatasetIdImport;
      parentRoute: typeof rootRoute;
    };
    '/portal/dashboard/': {
      id: '/portal/dashboard/';
      path: '/dashboard';
      fullPath: '/portal/dashboard';
      preLoaderRoute: typeof PortalDashboardIndexImport;
      parentRoute: typeof PortalImport;
    };
    '/portal/datasets/': {
      id: '/portal/datasets/';
      path: '/datasets';
      fullPath: '/portal/datasets';
      preLoaderRoute: typeof PortalDatasetsIndexImport;
      parentRoute: typeof PortalImport;
    };
    '/portal/projects/': {
      id: '/portal/projects/';
      path: '/projects';
      fullPath: '/portal/projects';
      preLoaderRoute: typeof PortalProjectsIndexImport;
      parentRoute: typeof PortalImport;
    };
    '/portal/user/': {
      id: '/portal/user/';
      path: '/user';
      fullPath: '/portal/user';
      preLoaderRoute: typeof PortalUserIndexImport;
      parentRoute: typeof PortalImport;
    };
  }
}

// Create and export the route tree

interface PortalRouteChildren {
  PortalDatasetsCreateRoute: typeof PortalDatasetsCreateRoute;
  PortalProjectsCreateRoute: typeof PortalProjectsCreateRoute;
  PortalDashboardIndexRoute: typeof PortalDashboardIndexRoute;
  PortalDatasetsIndexRoute: typeof PortalDatasetsIndexRoute;
  PortalProjectsIndexRoute: typeof PortalProjectsIndexRoute;
  PortalUserIndexRoute: typeof PortalUserIndexRoute;
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDatasetsCreateRoute: PortalDatasetsCreateRoute,
  PortalProjectsCreateRoute: PortalProjectsCreateRoute,
  PortalDashboardIndexRoute: PortalDashboardIndexRoute,
  PortalDatasetsIndexRoute: PortalDatasetsIndexRoute,
  PortalProjectsIndexRoute: PortalProjectsIndexRoute,
  PortalUserIndexRoute: PortalUserIndexRoute
};

const PortalRouteWithChildren = PortalRoute._addFileChildren(PortalRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/portal': typeof PortalRouteWithChildren;
  '/auth/confirm-email-code': typeof AuthConfirmEmailCodeRoute;
  '/auth/create-account': typeof AuthCreateAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/public/datasets': typeof PublicDatasetsRoute;
  '/setup': typeof SetupIndexRoute;
  '/portal/datasets/create': typeof PortalDatasetsCreateRoute;
  '/portal/projects/create': typeof PortalProjectsCreateRoute;
  '/public/dataset/$datasetId': typeof PublicDatasetDatasetIdRoute;
  '/portal/dashboard': typeof PortalDashboardIndexRoute;
  '/portal/datasets': typeof PortalDatasetsIndexRoute;
  '/portal/projects': typeof PortalProjectsIndexRoute;
  '/portal/user': typeof PortalUserIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/portal': typeof PortalRouteWithChildren;
  '/auth/confirm-email-code': typeof AuthConfirmEmailCodeRoute;
  '/auth/create-account': typeof AuthCreateAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/public/datasets': typeof PublicDatasetsRoute;
  '/setup': typeof SetupIndexRoute;
  '/portal/datasets/create': typeof PortalDatasetsCreateRoute;
  '/portal/projects/create': typeof PortalProjectsCreateRoute;
  '/public/dataset/$datasetId': typeof PublicDatasetDatasetIdRoute;
  '/portal/dashboard': typeof PortalDashboardIndexRoute;
  '/portal/datasets': typeof PortalDatasetsIndexRoute;
  '/portal/projects': typeof PortalProjectsIndexRoute;
  '/portal/user': typeof PortalUserIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/portal': typeof PortalRouteWithChildren;
  '/auth/confirm-email-code': typeof AuthConfirmEmailCodeRoute;
  '/auth/create-account': typeof AuthCreateAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/public/datasets': typeof PublicDatasetsRoute;
  '/setup/': typeof SetupIndexRoute;
  '/portal/datasets/create': typeof PortalDatasetsCreateRoute;
  '/portal/projects/create': typeof PortalProjectsCreateRoute;
  '/public/dataset/$datasetId': typeof PublicDatasetDatasetIdRoute;
  '/portal/dashboard/': typeof PortalDashboardIndexRoute;
  '/portal/datasets/': typeof PortalDatasetsIndexRoute;
  '/portal/projects/': typeof PortalProjectsIndexRoute;
  '/portal/user/': typeof PortalUserIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/portal'
    | '/auth/confirm-email-code'
    | '/auth/create-account'
    | '/auth/login'
    | '/public/datasets'
    | '/setup'
    | '/portal/datasets/create'
    | '/portal/projects/create'
    | '/public/dataset/$datasetId'
    | '/portal/dashboard'
    | '/portal/datasets'
    | '/portal/projects'
    | '/portal/user';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/portal'
    | '/auth/confirm-email-code'
    | '/auth/create-account'
    | '/auth/login'
    | '/public/datasets'
    | '/setup'
    | '/portal/datasets/create'
    | '/portal/projects/create'
    | '/public/dataset/$datasetId'
    | '/portal/dashboard'
    | '/portal/datasets'
    | '/portal/projects'
    | '/portal/user';
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/auth/confirm-email-code'
    | '/auth/create-account'
    | '/auth/login'
    | '/public/datasets'
    | '/setup/'
    | '/portal/datasets/create'
    | '/portal/projects/create'
    | '/public/dataset/$datasetId'
    | '/portal/dashboard/'
    | '/portal/datasets/'
    | '/portal/projects/'
    | '/portal/user/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PortalRoute: typeof PortalRouteWithChildren;
  AuthConfirmEmailCodeRoute: typeof AuthConfirmEmailCodeRoute;
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  PublicDatasetsRoute: typeof PublicDatasetsRoute;
  SetupIndexRoute: typeof SetupIndexRoute;
  PublicDatasetDatasetIdRoute: typeof PublicDatasetDatasetIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  AuthConfirmEmailCodeRoute: AuthConfirmEmailCodeRoute,
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthLoginRoute: AuthLoginRoute,
  PublicDatasetsRoute: PublicDatasetsRoute,
  SetupIndexRoute: SetupIndexRoute,
  PublicDatasetDatasetIdRoute: PublicDatasetDatasetIdRoute
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/portal",
        "/auth/confirm-email-code",
        "/auth/create-account",
        "/auth/login",
        "/public/datasets",
        "/setup/",
        "/public/dataset/$datasetId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/portal": {
      "filePath": "portal.tsx",
      "children": [
        "/portal/datasets/create",
        "/portal/projects/create",
        "/portal/dashboard/",
        "/portal/datasets/",
        "/portal/projects/",
        "/portal/user/"
      ]
    },
    "/auth/confirm-email-code": {
      "filePath": "auth/confirm-email-code.tsx"
    },
    "/auth/create-account": {
      "filePath": "auth/create-account.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/public/datasets": {
      "filePath": "public/datasets.tsx"
    },
    "/setup/": {
      "filePath": "setup/index.tsx"
    },
    "/portal/datasets/create": {
      "filePath": "portal/datasets/create.tsx",
      "parent": "/portal"
    },
    "/portal/projects/create": {
      "filePath": "portal/projects/create.tsx",
      "parent": "/portal"
    },
    "/public/dataset/$datasetId": {
      "filePath": "public/dataset.$datasetId.tsx"
    },
    "/portal/dashboard/": {
      "filePath": "portal/dashboard/index.tsx",
      "parent": "/portal"
    },
    "/portal/datasets/": {
      "filePath": "portal/datasets/index.tsx",
      "parent": "/portal"
    },
    "/portal/projects/": {
      "filePath": "portal/projects/index.tsx",
      "parent": "/portal"
    },
    "/portal/user/": {
      "filePath": "portal/user/index.tsx",
      "parent": "/portal"
    }
  }
}
ROUTE_MANIFEST_END */
