/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as PublicDatasetsImport } from './routes/public/datasets';
import { Route as AuthLoginImport } from './routes/auth/login';
import { Route as AuthCreateAccountImport } from './routes/auth/create-account';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any);

const PublicDatasetsRoute = PublicDatasetsImport.update({
  id: '/public/datasets',
  path: '/public/datasets',
  getParentRoute: () => rootRoute
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute
} as any);

const AuthCreateAccountRoute = AuthCreateAccountImport.update({
  id: '/auth/create-account',
  path: '/auth/create-account',
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/create-account': {
      id: '/auth/create-account';
      path: '/auth/create-account';
      fullPath: '/auth/create-account';
      preLoaderRoute: typeof AuthCreateAccountImport;
      parentRoute: typeof rootRoute;
    };
    '/auth/login': {
      id: '/auth/login';
      path: '/auth/login';
      fullPath: '/auth/login';
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof rootRoute;
    };
    '/public/datasets': {
      id: '/public/datasets';
      path: '/public/datasets';
      fullPath: '/public/datasets';
      preLoaderRoute: typeof PublicDatasetsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/auth/create-account': typeof AuthCreateAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/public/datasets': typeof PublicDatasetsRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/auth/create-account': typeof AuthCreateAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/public/datasets': typeof PublicDatasetsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/auth/create-account': typeof AuthCreateAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/public/datasets': typeof PublicDatasetsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/auth/create-account' | '/auth/login' | '/public/datasets';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/auth/create-account' | '/auth/login' | '/public/datasets';
  id: '__root__' | '/' | '/auth/create-account' | '/auth/login' | '/public/datasets';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  PublicDatasetsRoute: typeof PublicDatasetsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthLoginRoute: AuthLoginRoute,
  PublicDatasetsRoute: PublicDatasetsRoute
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/create-account",
        "/auth/login",
        "/public/datasets"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/create-account": {
      "filePath": "auth/create-account.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/public/datasets": {
      "filePath": "public/datasets.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
